config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'
  # get 'categories', to: 'categories#index'
  # get 'categories/new', to: 'categories#new'
  # post 'categories', to: 'categories#create'
  resources :categories do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
 
  validates :category, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :task, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #:confirmable, :lockable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def show
  end

  def edit
    
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def index
    @tasks = @category.tasks
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)
    if @task.save
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:task, :details, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category) do |f|  %>
  <%= f.text_field :category %>
  <%= f.submit%>
<%end%>

app/views/categories/create.html.erb
<h1>Create a category</h1>

app/views/categories/edit.html.erb
Edit category detail

<%= render 'form'%>

<%= link_to 'return', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th colspan="4">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td> <%= category.category %> </td>
      <td> <%= link_to 'show', category_path(category.id) %> </td>
      <td> <%= link_to 'edit', edit_category_path(category.id) %> </td>
      <td> <%= link_to 'delete', category_path(category.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure"} %> </td>
      <td> <%= link_to 'add task', new_category_task_path(category) %> </td>
    </tr>
  <%end%>
  </tbody>
</table>

<%= link_to 'Create a category', new_category_path%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form'%>

<%= link_to 'return', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.category %></h1>

<ul>
  <% @category.tasks.each do |task| %>
    <li> 
      <%= task.task %> 
      <%= link_to 'show', category_task_path(@category,task) %>
      <%= link_to 'edit', edit_category_task_path(@category, task) %>
    </li>
  <%end%>
</ul>


<%= link_to 'return',  categories_path%>

app/views/layouts/_notice.html.erb
<%# <% flash.each do |name,msg| %> %>
  <%# <%= msg%> %>
<%# <%end%> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p>
      <%= notice %>
    </p>
    <p>
      <%= alert %>
    </p>
    <% if user_signed_in?%>
      <%= link_to 'Sign out',destroy_user_session_path, data:{turbo_method: :delete} %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [@category, @task] do |f| %>
  <%= f.text_field :task, placeholder: 'task name' %><br/>
  <%= f.text_field :details, placeholder: 'details' %><br/>
  <%= f.submit 'Submit'%>
<%end%>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<%= link_to 'return', categories_path%>

app/views/tasks/index.html.erb
<h1>Tasks for this category</h1>

app/views/tasks/new.html.erb
<%= render 'form' %>

<%= link_to 'return', categories_path%>

app/views/tasks/show.html.erb
<h1> <%= @task.task %> </h1>
<h2> <%= @task.details %> </h2>

<%= link_to 'return', category_path(@category.id) %>